/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import ConexionSql.Comexion_Sql_Server;
import ConexionSql.Conexion_postgresql;
import ConexionSql.conexion_MYSQL;
import ConexionSql.conexion_Oracle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class interfaz_user extends javax.swing.JFrame {

    /**
     * Creates new form interfaz_user
     */
    public interfaz_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MYSQL_BUTTON = new javax.swing.JButton();
        POSTGRESQL_BUTTON = new javax.swing.JButton();
        ORACLE_BUTTON = new javax.swing.JButton();
        SQL_SERVER_BUTTON = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MYSQL_BUTTON.setText("MYSQL");
        MYSQL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MYSQL_BUTTONActionPerformed(evt);
            }
        });

        POSTGRESQL_BUTTON.setText("POSTGRESQL");
        POSTGRESQL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POSTGRESQL_BUTTONActionPerformed(evt);
            }
        });

        ORACLE_BUTTON.setText("ORACLE");
        ORACLE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORACLE_BUTTONActionPerformed(evt);
            }
        });

        SQL_SERVER_BUTTON.setText("SQL SERVER");
        SQL_SERVER_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQL_SERVER_BUTTONActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MYSQL_BUTTON)
                .addGap(18, 18, 18)
                .addComponent(ORACLE_BUTTON)
                .addGap(18, 18, 18)
                .addComponent(SQL_SERVER_BUTTON)
                .addGap(18, 18, 18)
                .addComponent(POSTGRESQL_BUTTON)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MYSQL_BUTTON)
                    .addComponent(ORACLE_BUTTON)
                    .addComponent(SQL_SERVER_BUTTON)
                    .addComponent(POSTGRESQL_BUTTON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MYSQL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MYSQL_BUTTONActionPerformed
        conexion_MYSQL cc = new conexion_MYSQL();
        Connection con = cc.conexionMysql();

        String[] titulos = {"nombre de las tablas"};
        String[] registro =new String[1];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String sql = "show tables";

        try {

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                registro[0] =rs.getString("Tables_in_proyectos");

                modelo.addRow(registro);
            }
            jTable1.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos: " + e);
        }

    }//GEN-LAST:event_MYSQL_BUTTONActionPerformed

    private void POSTGRESQL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POSTGRESQL_BUTTONActionPerformed
        Conexion_postgresql cc = new Conexion_postgresql();
        Connection con = cc.Conexion_postgresql();
        
        String[] titulo = {"Nombres de las tablas"};
        String[] registro = new String[1];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulo);
        
        String sql = "SELECT tablename FROM pg_catalog.pg_tables where schemaname='public'";
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {                
                registro[0] = rs.getString("tablename");
                modelo.addRow(registro);
            }
            jTable1.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos: " + e);
        }
    }//GEN-LAST:event_POSTGRESQL_BUTTONActionPerformed

    private void ORACLE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORACLE_BUTTONActionPerformed
        conexion_Oracle cc = new conexion_Oracle();
        Connection con = cc.conexionoracle();
        
        String[] titulo = {"Nombres de las tablas"};
        String[] registro = new String[1];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulo);
        
        String sql = "SELECT TABLE_NAME FROM USER_TABLES where tablespace_name = 'PROYECTOS'";
                
        try {
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {                
                registro[0] = rs.getString("TABLE_NAME");
                modelo.addRow(registro);
            }
            jTable1.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos: " + e);
        }
        
        
        
    }//GEN-LAST:event_ORACLE_BUTTONActionPerformed

    private void SQL_SERVER_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SQL_SERVER_BUTTONActionPerformed
        Comexion_Sql_Server cc = new Comexion_Sql_Server();
        Connection con = cc.Conexion_sql_server();
        
        String[] titulo = {"Nombres de las tablas"};
        String[] registro = new String[1];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulo);
        
        String sql = "SELECT name FROM SYSOBJECTS WHERE xtype = 'U'";
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {                
                registro[0] = rs.getString("name");
                modelo.addRow(registro);
            }
            jTable1.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos: " + e);
        }
    }//GEN-LAST:event_SQL_SERVER_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MYSQL_BUTTON;
    private javax.swing.JButton ORACLE_BUTTON;
    private javax.swing.JButton POSTGRESQL_BUTTON;
    private javax.swing.JButton SQL_SERVER_BUTTON;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
